config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :projects
  resources :materials
  root 'welcome#index'
  authenticated :user do
    root to: "dashboard#index", as: :authenticated_root
  end
  get "about" => "welcome#about"
  get "profile" => "profile#index"
  get "settings" => "settings#index"
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  layout :layout_by_resource

  def after_sign_in_path_for(resource)
    projects_path
  end

protected
  def layout_by_resource
    if devise_controller?
      "application_unauthorized"
    elsif user_signed_in?
      "application"
    else
      "landing"
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  def index
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = current_user.projects.all
  end

  def show
  end

  def new
    @project = current_user.projects.new
  end

  def edit
  end

  def create
    @project = current_user.projects.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
        format.js   { redirect_to @project, notice: 'Project was successfully created.' }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
        format.js   { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
        format.js   { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
        format.js   { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
      format.js   { format.js   { render :destroy, status: :ok, location: @project } }
    end
  end

  private
    def set_project
      @project = current_user.projects.find(params[:id])
    end

    def project_params
      params.require(:project).permit(:name, :description, :address, :contact_person, :contact_number)
    end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def is_active?(page_name)
    "active" if params[:controller] == page_name
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Specifi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'sidebar' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  <div id="wrapper">
    <!-- Sidebar -->
    <div id="sidebar-wrapper">
      <ul class="sidebar-nav">
        <li><a href="#" class="text-center"><%= image_tag "logo.svg"%></a></li>
        <li></br></li>
        <li><%= link_to content_tag(:i, ' Dashboard', class: "fa fa-dashboard"), authenticated_root_path, class: is_active?("dashboard") %></li>
        <li><%= link_to content_tag(:i, ' Projects', class: "fa fa-bars"), projects_path, class: is_active?("projects") %></li>
        <li><%= link_to content_tag(:i, ' Materials', class: "fa fa-archive"), materials_path, class: is_active?("materials") %></li>
        <li><%= link_to content_tag(:i, ' Profile', class: "fa fa-user"), profile_path, class: is_active?("profile") %></li>
        <li><%= link_to content_tag(:i, ' Settings', class: "fa fa-cog"), settings_path, class: is_active?("settings") %></li>
        <li><%= link_to content_tag(:i, ' Logout', class: "fa fa-sign-out"), destroy_user_session_path, method: :delete %></li>

      </ul>
    </div>


    <div id="page-content-wrapper">
      <div class="content-header">
        <h1>
          <a id="menu-toggle" href="#" class="btn btn-default"><%= fa_icon "navicon" %></a>
          <%= yield(:title) %>
        </h1>
      </div>
    </div>
    <!-- Keep all page content within the page-content inset div! -->
    <div class="page-content inset">
      <%= yield %>
    </div>
  </div>

  <!-- Custom JavaScript for the Menu Toggle -->
  <script>

    window.onload = function() {

  var mySwiper = new Swiper('.swiper-container',{
    slidesPerView: 'auto'
  })

    }

    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("active");
    });

    $('body').on('hidden.bs.modal', '.modal', function () {
      $(this).removeData('bs.modal');
    });
    $('body').on('hidden.bs.modal', '#confirm-delete', function () {
      $(this).remove();
    });
  </script>
</body>
</html>

app/views/layouts/application_unauthorized.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Specifi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/layouts/landing.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Specifi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'landing' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  <div id="landing">
    <nav class="navbar navbar-inverse navbar-static-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">SPECIFI</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="navbar">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Login", new_user_session_path %></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    <%= yield %>
  </div>
</body>
</html>

app/views/projects/_form.html.erb
<div id="project-form">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="">Project</h4>
  </div>

  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% modal ||= false %>
  <% remote = modal ? true : false %>

  <%= form_for(@project, remote: remote, html: {class: "project-form", role: :form, 'data-model' => 'project'}) do |f| %>
    <div class="modal-body">
      <% if @project.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

          <ul>
          <% @project.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <div class="form-group">
        <%= f.label :name, class: 'control-label' %><br>
        <%= f.text_field :name, class: 'form-control' %>
        <span class="help-block"></span>
      </div>
      <div class="form-group">
        <%= f.label :contact_person, class: 'control-label' %><br>
        <%= f.text_field :contact_person, class: 'form-control' %>
        <span class="help-block"></span>
      </div>
      <div class="form-group">
        <%= f.label :contact_number, class: 'control-label' %><br>
        <%= f.text_field :contact_number, class: 'form-control' %>
        <span class="help-block"></span>
      </div>
      <div class="form-group">
        <%= f.label :address, class: 'control-label' %><br>
        <%= f.text_field :address, class: 'form-control' %>
        <span class="help-block"></span>
      </div>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      <%= f.submit class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/projects/_project_row.html.erb
<a href="<%= project_path(project) %>" class="col-xs-8">
  <div class="row visible-sm-block visible-xs-block">
    <div class="swiper-container">
      <div class="swiper-wrapper">
        <div class="swiper-slide swiper-slide-active">
          <div class="title">
            <div class="col-xs-12">
              <address>
                <strong><%= project.name %></strong><br>
                <i class="fa fa-user"> <%= project.contact_person %></i><br>
                <i class="fa fa-phone"> <%= project.contact_number %></i><br>
              </address>
              <small><em>Last updated: <%= time_ago_in_words(project.updated_at) %> ago</em></small>
            </div>
          </div>
        </div>

        <div class="swiper-slide">
          <div class="title">Slide 6</div>
        </div>
      </div>
    </div>
  </div>




  <div class="row visible-md-block visible-lg-block">
      <div class="col-md-4">
        <%= project.name %>
      </div>
      <div class="col-md-4">
        <%= project.contact_person %>
      </div>
      <div class="col-md-4">
        <%= project.contact_number %>
      </div>
  </div>
</a>
<div class="col-xs-4 actions row visible-md-block visible-lg-block">
  <div class="row">
    <div class="col-md-6 col-xs-6">
      <%= link_to content_tag(:i, '', class: "fa fa-edit"), "#",
                  data:{
                    toggle:"modal",
                    target:"#project-modal",
                    remote: "#{edit_project_path(project)} #project-form"
                  } %>
    </div>
    <div class="col-md-6 col-xs-6">
      <%= link_to content_tag(:i, '', class: "fa fa-trash-o"), project,
                  data: {remote: true, confirm: "Are you sure you want to delete '#{project.name}'?"},
                  method: :delete %>

    </div>
  </div>
</div>

app/views/projects/create.js.erb
$("#project-list").append("<%= j render partial:"project_row", locals: {project: @project } %>");
$('#project-modal').modal_success();

app/views/projects/destroy.js.erb
$("<%= "#project-#{@project.id}" %>").remove();
$("#confirm-delete").modal('hide');

app/views/projects/edit.html.erb
<%= render "form", modal: true %>

app/views/projects/index.html.erb
<div class="row">
  <div class="col-xs-6 col-md-10">
	  <p class="lead">This is the list of all your projects.</p>
	</div>
	<div class="col-xs-6 col-md-2">
		<%= link_to "#",
								class: "btn btn-default",
								data:{
									toggle:"modal",
									target:"#project-modal",
									remote: "#{new_project_path} #project-form"
								} do %>

								<%= fa_icon "plus" %> New Product
		<% end %>
	</div>
</div>

<div class="row">
	<div id="project-list">
		<div class="row table-header">
			<div class="col-xs-8 hidden-sm hidden-xs">
				<div class="row">
					<div class="col-md-4">
						<h5><small>NAME</small></h5>
					</div>
					<div class="col-md-4">
						<h5><small>CONTACT PERSON</small></h5>
					</div>
					<div class="col-md-4">
						<h5><small>PHONE</small></h5>
					</div>
				</div>
			</div>
		</div>
		<% @projects.each do |project| %>
			<div id='<%= "project-#{project.id}" %>' class="row project-list-item">
				<%= render partial: "project_row", locals: { project: project } %>
			</div>
		<% end %>
	</div>

	<div class="modal fade" id="project-modal" tabindex="-1" role="dialog" aria-labelledby="" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
			</div>
		</div>
	</div>
</div>

app/views/projects/new.html.erb
<%= render "form" %>

app/views/projects/show.html.erb
<% content_for :title, @project.name %>
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/projects/show.js.erb
$("<%= "#project-#{@project.id}" %>").html("<%= j render partial:"project_row", locals: {project: @project } %>");
$('#project-modal').modal_success();

app/views/welcome/about.html.erb
<h1>About Us</h1>